import { assert, it } from "poku";

import * as barrel from "./utils.js";

// The authoritative list of the 261 public names exported by the
// `lib/helpers/utils.js` re-export barrel. This list is inlined (not loaded
// from a fixture) so it cannot be accidentally regenerated. It is verified
// against commit 0cbce22b (the pre-decomposition monolith) and must stay
// byte-identical across every batch of the v13/03 decomposition.
const EXPECTED_NAMES = [
  "BLOCKED_HOST_ERROR_CODE",
  "CARGO_CMD",
  "CDXGEN_SPDX_CREATED_BY",
  "CDXGEN_TEMP_DIR",
  "CDXGEN_VERSION",
  "CLJ_CMD",
  "DEBUG_MODE",
  "DOTNET_CMD",
  "DRY_RUN_ERROR_CODE",
  "FETCH_LICENSE",
  "GCC_CMD",
  "GO_CMD",
  "JAVA_CMD",
  "LEIN_CMD",
  "MAX_BUFFER",
  "NODE_CMD",
  "NPM_CMD",
  "PACKAGE_MANAGER_ALIASES",
  "PREFER_MAVEN_DEPS_TREE",
  "PROJECT_TYPE_ALIASES",
  "PYTHON_CMD",
  "PYTHON_EXCLUDED_COMPONENTS",
  "RUBY_CMD",
  "RUSTC_CMD",
  "SEARCH_MAVEN_ORG",
  "SWIFT_CMD",
  "TABLE_BORDER_STYLE",
  "TIMEOUT_MS",
  "YARN_CMD",
  "addEvidenceForDotnet",
  "addEvidenceForImports",
  "addLicenseText",
  "adjustLicenseInformation",
  "attachIdentityTools",
  "buildObjectForCocoaPod",
  "cdxgenAgent",
  "checksumFile",
  "collectExecutables",
  "collectJarNS",
  "collectMvnDependencies",
  "collectSharedLibs",
  "commandsExecuted",
  "componentSorter",
  "composePomXmlUrl",
  "convertJarNSToPackages",
  "convertOSQueryResults",
  "createBlockedHostError",
  "createDryRunError",
  "createNpmWorkspacePurl",
  "createUVLock",
  "derivePythonLockMetadataFileName",
  "dirNameStr",
  "encodeForPurl",
  "executeAlpmList",
  "executeApkList",
  "executeAtom",
  "executeDpkgList",
  "executeEqueryList",
  "executePodCommand",
  "executeRpmList",
  "extractJarArchive",
  "extractLicenseCommentFromPomXml",
  "extractPathEnv",
  "extractToolRefs",
  "fetchPomXml",
  "fetchPomXmlAsJson",
  "findAppModules",
  "findLicenseId",
  "findLocalMvnArtifact",
  "findPnpmPackagePath",
  "frameworksList",
  "generatePixiLockFile",
  "getAllFiles",
  "getAllFilesWithIgnore",
  "getAtomCommand",
  "getCppModules",
  "getCratesMetadata",
  "getDartMetadata",
  "getDefaultBomAuditCategories",
  "getGithubUrlParts",
  "getGoPkgComponent",
  "getGoPkgLicense",
  "getJarClasses",
  "getJavaCommand",
  "getKnownLicense",
  "getLicenses",
  "getMavenCommand",
  "getMillCommand",
  "getMvnMetadata",
  "getNpmMetadata",
  "getNugetMetadata",
  "getOSPackageForFile",
  "getPipFrozenTree",
  "getPipTreeForPackages",
  "getPomPropertiesFromMavenDir",
  "getPropertyGroupTextNodes",
  "getPyMetadata",
  "getPyModules",
  "getPythonCommand",
  "getRecordedActivities",
  "getRepoLicense",
  "getRuntimeInformation",
  "getSwiftPackageMetadata",
  "getTimestamp",
  "getTmpDir",
  "getVersionNumPnpm",
  "guessLicenseId",
  "guessPypiMatchingVersion",
  "hasAnyProjectType",
  "hasDangerousUnicode",
  "identifyFlow",
  "includeMavenTestScope",
  "inferJarGroupFromManifest",
  "isAllowedHttpHost",
  "isBun",
  "isDeno",
  "isDryRun",
  "isDryRunError",
  "isFeatureEnabled",
  "isMac",
  "isNode",
  "isPackageManagerAllowed",
  "isPartialTree",
  "isSecureMode",
  "isSensitiveEnvironmentVariableName",
  "isSpdxLicenseExpression",
  "isValidDriveRoot",
  "isValidIriReference",
  "isWin",
  "locateGenericPackage",
  "mapConanPkgRefToPurlStringAndNameAndVersion",
  "metadata_cache",
  "multiChecksumFile",
  "parseBazelActionGraph",
  "parseBazelBuild",
  "parseBazelSkyframe",
  "parseBdistMetadata",
  "parseBitbucketPipelinesFile",
  "parseBowerJson",
  "parseCUsageSlice",
  "parseCabalData",
  "parseCargoAuditableData",
  "parseCargoData",
  "parseCargoDependencyData",
  "parseCargoManifestDependencyData",
  "parseCargoTomlData",
  "parseCljDep",
  "parseCloudBuildData",
  "parseCmakeDotFile",
  "parseCmakeLikeFile",
  "parseCocoaDependency",
  "parseColliderLockData",
  "parseComposerJson",
  "parseComposerLock",
  "parseConanData",
  "parseConanLockData",
  "parseContainerFile",
  "parseContainerSpecData",
  "parseCsPkgData",
  "parseCsPkgLockData",
  "parseCsProjAssetsData",
  "parseCsProjData",
  "parseEdnData",
  "parseFlakeLock",
  "parseFlakeNix",
  "parseGitHubWorkflowData",
  "parseGoListDep",
  "parseGoModData",
  "parseGoModGraph",
  "parseGoModWhy",
  "parseGoModulesTxt",
  "parseGoVersionData",
  "parseGopkgData",
  "parseGosumData",
  "parseHelmYamlData",
  "parseJarManifest",
  "parseKVDep",
  "parseLeinDep",
  "parseLeinMap",
  "parseLeiningenData",
  "parseLicenseEntryOrArrayFromPomXml",
  "parseMakeDFile",
  "parseMavenArgs",
  "parseMavenTree",
  "parseMavenTreeJson",
  "parseMillDependency",
  "parseMinJs",
  "parseMixLockData",
  "parseNodeShrinkwrap",
  "parseNupkg",
  "parseNuspecData",
  "parseOpenapiSpecData",
  "parsePackageJsonName",
  "parsePaketLockData",
  "parsePiplockData",
  "parsePixiLockFile",
  "parsePixiTomlFile",
  "parsePkgJson",
  "parsePkgLock",
  "parsePnpmLock",
  "parsePnpmWorkspace",
  "parsePodfileLock",
  "parsePodfileTargets",
  "parsePom",
  "parsePomProperties",
  "parsePomXml",
  "parsePrivadoFile",
  "parsePubLockData",
  "parsePubYamlData",
  "parsePyLockData",
  "parsePyProjectTomlFile",
  "parsePyRequiresDist",
  "parseReqEnvMarkers",
  "parseReqFile",
  "parseSetupPyFile",
  "parseSwiftJsonTree",
  "parseSwiftJsonTreeObject",
  "parseSwiftResolved",
  "parseYarnLock",
  "parseYarnWorkspace",
  "pnpmMetadata",
  "purlFromUrlString",
  "readEnvironmentVariable",
  "readLicenseText",
  "readZipEntry",
  "recomputeScope",
  "recordActivity",
  "recordDecisionActivity",
  "recordDiscoveryActivity",
  "recordEnvironmentRead",
  "recordObservedActivity",
  "recordPolicyActivity",
  "recordSensitiveFileRead",
  "recordSymlinkResolution",
  "recurseImageNameLookup",
  "remoteHostsAccessed",
  "repoMetadataToGitHubApiUrl",
  "resetActivityContext",
  "resetRecordedActivities",
  "retrieveCdxgenPluginVersion",
  "retrieveCdxgenVersion",
  "safeCopyFileSync",
  "safeExistsSync",
  "safeExtractArchive",
  "safeMkdirSync",
  "safeMkdtempSync",
  "safeRmSync",
  "safeSpawnSync",
  "safeUnlinkSync",
  "safeWriteSync",
  "setActivityContext",
  "setDryRunMode",
  "shouldFetchLicense",
  "shouldFetchPackageMetadata",
  "shouldFetchVCS",
  "shouldRunPredictiveBomAudit",
  "splitCommandArgs",
  "toCamel",
  "toGitHubApiUrl",
  "trimJarGroupSuffix",
  "yarnLockToIdentMap",
];

it("utils.js barrel exports exactly the expected 261 public names", () => {
  const actualNames = Object.keys(barrel).sort();
  const expected = [...EXPECTED_NAMES].sort();
  assert.strictEqual(
    actualNames.length,
    261,
    "barrel must export exactly 261 names",
  );
  assert.deepStrictEqual(
    actualNames,
    expected,
    "barrel name set drifted from the committed list",
  );
});

it("accessing every exported name is safe (no TDZ/cycle breakage)", () => {
  // A TDZ or broken-cycle binding throws ReferenceError on access. Some names
  // are legitimately `undefined` when their env vars are unset
  // (CDXGEN_SPDX_CREATED_BY, FETCH_LICENSE), so we check for thrown errors,
  // not for truthy values.
  const broken = [];
  for (const name of Object.keys(barrel)) {
    try {
      // Probing by name is the point: a throwing binding must be reported
      // individually, and static access cannot enumerate the barrel.
      // biome-ignore lint/performance/noDynamicNamespaceImportAccess: see above
      barrel[name];
    } catch {
      broken.push(name);
    }
  }
  assert.deepStrictEqual(
    broken,
    [],
    `these names throw on access: ${broken.join(", ")}`,
  );
});

it("internal names _clearMetadataCache and temporaryFiles are absent from the barrel", () => {
  assert.ok(
    !("_clearMetadataCache" in barrel),
    "_clearMetadataCache must not leak into the barrel",
  );
  assert.ok(
    !("temporaryFiles" in barrel),
    "temporaryFiles must not leak into the barrel",
  );
});
