blockExoticSubdeps: true
cleanupUnusedCatalogs: true
lockfileIncludeTarballUrl: true
minimumReleaseAge: '4320'
minimumReleaseAgeExclude:
  - '@cdxgen/*'
  - '@appthreat/*'
  - 'typescript'
  - '@typescript/*'
optimisticRepeatInstall: true
packages:
  - 'packages/*'
preferSymlinkedExecutables: false
strictDepBuilds: true
trustPolicy: no-downgrade
