export declare function getHbomCommandDiagnostics(bomJson: any): any;
export declare function getHbomCommandDiagnosticSummary(bomJson: any): {
    actionableDiagnosticCount: any;
    commandDiagnosticCount: any;
    commandDiagnostics: any;
    commandErrorCount: any;
    commandErrorIds: string[];
    diagnosticIssues: string[];
    installHintCount: number;
    installHints: string[];
    missingCommandCount: any;
    missingCommandIds: string[];
    missingCommands: string[];
    partialSupportCount: any;
    partialSupportIds: string[];
    permissionDeniedCommands: string[];
    permissionDeniedCount: any;
    permissionDeniedIds: string[];
    privilegeHintCount: number;
    privilegeHints: string[];
    requiresPrivilegedEnrichment: boolean;
    timeoutIds: string[];
    timeoutCount: any;
};
export declare function isHbomLikeBom(bomJson: any): any;
export declare function getHbomHardwareClass(component: any): any;
export declare function getHbomHardwareClassCounts(components?: any[]): {
    hardwareClass: any;
    count: any;
}[];
export declare function formatHbomHardwareClassSummary(hardwareClassCounts?: any[]): string;
export declare function getHbomSummary(bomJson: any): {
    actionableDiagnosticCount: any;
    architecture: any;
    collectorProfile: any;
    commandDiagnosticCount: any;
    commandDiagnostics: any;
    commandErrorCount: any;
    commandErrorIds: string[];
    componentCount: any;
    diagnosticIssues: string[];
    evidenceCommandCount: any;
    evidenceCommands: any;
    evidenceFileCount: any;
    evidenceFiles: any;
    hardwareClassCount: number;
    hardwareClassCounts: {
        hardwareClass: any;
        count: any;
    }[];
    identifierPolicy: any;
    installHintCount: number;
    installHints: string[];
    manufacturer: any;
    metadataName: any;
    metadataType: any;
    missingCommandCount: any;
    missingCommandIds: string[];
    missingCommands: string[];
    partialSupportCount: any;
    partialSupportIds: string[];
    platform: any;
    permissionDeniedCommands: string[];
    permissionDeniedCount: any;
    permissionDeniedIds: string[];
    privilegeHintCount: number;
    privilegeHints: string[];
    requiresPrivilegedEnrichment: boolean;
    timeoutIds: string[];
    timeoutCount: any;
    topHardwareClasses: {
        hardwareClass: any;
        count: any;
    }[];
};
//# sourceMappingURL=hbomAnalysis.d.ts.map