export declare const toResolvedValueArray: (value: any) => any;
export declare const resolvedValueKey: (value: any) => string;
export declare const mergeResolvedValues: (...values: any[]) => any;
export declare const filterResolvedValues: (value: any, predicate: any) => any;
export declare const hasOnlyResolvedValues: (value: any, predicate: any) => any;
export declare const getStaticObjectProperty: (objectValue: any, propertyName: any) => any;
export declare const deriveStaticNarrowingsFromCondition: (astNode: any, branchTaken: any, getLiteralStringValue: any) => any;
export declare const resolveStaticValue: (astNode: any, staticValueByName: any, getLiteralStringValue: any, getMemberExpressionPropertyName: any, depth?: number) => any;
export declare const deriveStaticNarrowingsFromSwitchCase: (switchCaseNode: any, switchStatementNode: any, staticValueByName: any, getLiteralStringValue: any, getMemberExpressionPropertyName: any) => Map<any, any> | undefined;
export declare const getScopedStaticValueByName: (path: any, staticValueByName: any, getLiteralStringValue: any, getMemberExpressionPropertyName: any) => Map<any, any>;
//# sourceMappingURL=analyzerScope.d.ts.map