export declare function isKosiKotlinLanguage(language: any): boolean;
/**
 * True when kosi is disabled by CDXGEN_KOSI_DISABLE (1/all/true) or --no-kosi.
 * The check happens before any binary resolution so a disabled run never
 * even looks for the plugin.
 */
export declare function kosiDisabled(): any;
/**
 * Orchestrates the kosi runs over src and returns the parsed reports: one
 * `all` pass (every slice kind, dependency tier) and one `reachable` pass
 * (call-graph reachability from the roots). The analysis is read-only and
 * offline: kosi never executes the project's build. A classpath.txt beside
 * the sources (the documented build-tool report) is passed through when
 * present.
 *
 * @param {string} src Directory to analyze.
 * @param {Object} options Configuration options.
 * @returns {Object|undefined} { report, reachableReport } or undefined.
 */
export declare function analyzeKosiProject(src: string, options?: Object): Object | undefined;
/**
 * Merges the reachable pass's evidence into the all pass's maps, mutating
 * the first argument.
 *
 * The reachable pass's slices are the all pass's INTERSECTED with call-graph
 * reachability from the roots, so every key it produces is a key the all pass
 * already has, and the unions below cannot add one. That made the second full
 * `--backend resolved --deps` analysis — the most expensive thing this arm
 * runs, and it runs it twice — contribute exactly nothing: the one fact it
 * computes, reachability, was discarded at the merge (the P23 review's R144).
 * It is recorded now, on the components whose evidence survived the
 * intersection, which is the signal an SBOM consumer prioritises with. kosi's
 * own schema deliberately stopped carrying `reachableFromRoots` per slice in
 * P22 because there it was a mode-level fact wearing a per-slice field's
 * clothes; here it is neither, it is the measured difference between two runs.
 */
export declare function mergeKosiEvidence(all: any, reachable: any): any;
/**
 * Services evidence: kosi's outbound services[] rows are already
 * CycloneDX-shaped.
 */
export declare function collectKosiServices(kosiReport?: {}, servicesMap?: {}): {};
/**
 * INBOUND endpoints: kosi's apiEndpoints[] rows are the routes the analysed
 * application itself serves, which `services[]` (kosi's OUTBOUND calls)
 * does not carry. Without this the whole inbound surface — the path
 * template, the framework that declared it, and above all whether anything
 * authenticates it — stopped at the kosi report and never reached the
 * SaaSBOM.
 *
 * One service per endpoint, named the way detectServicesFromOpenAPI names
 * its own (`service-<path>-<method>`), so an OpenAPI spec and a kosi run
 * over the same route converge on one entry instead of two.
 *
 * `authenticated` is left UNDEFINED when the endpoint declares no
 * authentication: kosi's empty list means "nothing was declared here",
 * which is not the same claim as "this route is unauthenticated", and
 * cdxgen's own detectors use undefined for exactly that unknown.
 *
 * @param {Object} kosiReport The parsed JSON generated by kosi.
 * @param {Object} servicesMap Map populated with detected service definitions
 * @returns {Object} The mutated services map
 */
export declare function collectKosiApiEndpoints(kosiReport?: Object, servicesMap?: Object): Object;
export declare function collectKosiEvidence(kosiReport?: {}, components?: any[]): {
    componentPropertiesMap: {};
    cryptoComponents: any[];
    cryptoGeneratePurls: {};
    dataFlowFrames: {};
    metadataProperties: any[];
    purlLocationMap: {};
};
//# sourceMappingURL=kosi.d.ts.map